slack message update trial 01

diff --git a/playwright.yml b/playwright.yml
--- a/playwright.yml
+++ b/playwright.yml
@@ -1,5 +1,4 @@
 name: Playwright Tests
-
 on:
   push:
     branches: [main, master]
@@ -51,13 +50,6 @@ jobs:
           name: ui-playwright-report
           path: playwright-report/
           retention-days: 30
-      - name: Upload Failed Test Artifacts
-        uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-            name: ui-failed-test-artifacts
-            path: path/to/failure/screenshots/
-            retention-days: 30    
 
       # New Step to Generate Slack Message from JSON Report for UI Tests
       - name: Generate Slack Message for UI Tests
@@ -110,100 +102,80 @@ jobs:
           name: api-playwright-report
           path: playwright-report/
           retention-days: 30
-      - name: Upload Failed Test Artifacts
-        uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: api-failed-test-artifacts
-          path: path/to/failure/screenshots/
-          retention-days: 30
 
       # New Step to Generate Slack Message from JSON Report for API Tests 
       - name: Generate Slack Message for API Tests 
-        run: |
+        run: | 
           node lib/slack_reporter.ts 
 
       # Notify Slack for API Test Results (dynamic message)
       - name: Notify Slack for API Test Results 
-        uses: rtCamp/action-slack-notify@v2 
+        uses : rtCamp/action-slack-notify@v2 
         env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_GREENKART_URL }} 
-          SLACK_CHANNEL: "#automate_greenkart_using_playwright_ts_api-run_report" 
-          SLACK_USERNAME: Playwright GitHub Actions 
-          SLACK_MESSAGE: |
+          SLACK_WEBHOOK:${{ secrets.SLACK_WEBHOOK_GREENKART_URL }} 
+          SLACK_CHANNEL:"#automate_greenkart_using_playwright_ts_api-run_report" 
+          SLACK_USERNAME:"Playwright GitHub Actions" 
+          SLACK_MESSAGE | 
             $(cat ./slack-message.txt)
 
   bdd-tests:
     name: Execute BDD Playwright Tests 
-    runs-on: ubuntu-latest 
-    env: 
-      SECRET_KEY: ${{ secrets.SECRET_KEY }} 
-    container:
-      image: mcr.microsoft.com/playwright:v1.48.1-jammy 
-    timeout-minutes: 60 
+    runs-on : ubuntu-latest 
+    env : 
+      SECRET_KEY:${{ secrets.SECRET_KEY }} 
+    container :
+      image:mcr.microsoft.com/playwright:v1.48.1-jammy 
+    timeout-minutes :60 
     steps:
-      - uses: actions/checkout@v4 
-      - uses: actions/setup-node@v4 
-        with:
-          node-version: lts/* 
-      - name: Cache Node.js modules 
-        uses: actions/cache@v4 
-        with:
-          path: ~/.npm 
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
-          restore-keys: |
+      - uses :actions/checkout@v4 
+      - uses :actions/setup-node@v4 
+        with :
+          node-version:lts/* 
+      - name :Cache Node.js modules 
+        uses :actions/cache@v4 
+        with :
+          path :~/.npm 
+          key:${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
+          restore-keys :|
             ${{ runner.os }}-node- 
-      - name: Install Dependencies 
-        run: npm ci 
-      - name: Install Playwright Browsers 
-        run: npx playwright install --with-deps 
-      - name: Generate BDD Files 
-        run: export ENV="ci" && npx bddgen --tags "@BDD" 
-      - name: Check if BDD Features File Exists 
-        run: |
-          if [ -d ".features-gen/features" ]; then echo "Features directory exists"; else echo "Error: Features directory missing"; exit 1; fi  
-      - name: Run BDD Tests  
-        run: export ENV="ci" && npx playwright test --project=bdd_chromium || echo "BDD Tests failed" >> test_failures.txt  
-      - name: Upload BDD Test Report  
-        uses: actions/upload-artifact@v4  
-        if: always()  
-        with:
-          name: bdd-playwright-report  
-          path: playwright-report/  
-          retention-days: 30  
-      - name: Upload Failed BDD Test Artifacts
-        uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: bdd-failed-test-artifacts
-          path: path/to/failure/screenshots/
-          retention-days: 30
+      - name :Install Dependencies 
+        run:npm ci 
+      - name :Install Playwright Browsers 
+        run:npx playwright install --with-deps 
+      - name :Generate BDD Files 
+        run :export ENV="ci" && npx bddgen --tags "@BDD" 
+      - name :Check if BDD Features File Exists 
+        run :| if [ -d ".features-gen/features" ]; then echo "Features directory exists"; else echo "Error Features directory missing"; exit 1; fi  
+      - name :Run BDD Tests  
+        run :export ENV="ci" && npx playwright test --project=bdd_chromium || echo "BDD Tests failed" >> test_failures.txt  
+      - name :Upload BDD Test Report  
+        uses :actions/upload-artifact@v4  
+        if :always()  
+        with :
+           name:bdd-playwright-report  
+           path :playwright-report/  
+           retention-days :30  
 
-      # New Step to Generate Slack Message from JSON Report for BDD Tests    
-      - name: Generate Slack Message for BDD Tests   
-        run: |
-          node lib/slack_reporter.ts    
+       # New Step to Generate Slack Message from JSON Report for BDD Tests    
+       - name :Generate Slack Message for BDD Tests   
+         run |    
+           node lib/slack_reporter.ts    
 
-      # Notify Slack for BDD Test Results (dynamic message)    
-      - name: Notify Slack for BDD Test Results    
-        uses: rtCamp/action-slack-notify@v2    
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_GREENKART_URL }}    
-          SLACK_CHANNEL: "#automate_greenkart_using_playwright_ts_api-run_report"    
-          SLACK_USERNAME: Playwright GitHub Actions    
-          SLACK_MESSAGE: |
-            $(cat ./slack-message.txt)
+       # Notify Slack for BDD Test Results (dynamic message)    
+       - name :Notify Slack for BDD Test Results    
+         uses :rtCamp/action-slack-notify@v2    
+         env :
+           SLACK_WEBHOOK:${{ secrets.SLACK_WEBHOOK_GREENKART_URL }}    
+           SLACK_CHANNEL:"#automate_greenkart_using_playwright_ts_api-run_report"    
+           SLACK_USERNAME:"Playwright GitHub Actions"    
+           SLACK_MESSAGE |    
+             $(cat ./slack-message.txt)
 
   # Final step to check for any failures across all test jobs  
   check-failures:
-    runs-on: ubuntu-latest   
-    needs: [ui-tests, api-tests, bdd-tests]   
+    runs-on:utf8=ubuntu-latest   
+    needs:[ui-tests, api-tests, bdd-tests]   
     steps:
-      - name: Check for Test Failures
-        run: |
-          if [ -f test_failures.txt ]; then
-            echo "One or more test suites failed."
-            exit 1
-          else
-            echo "All tests passed successfully."
-          fi
+     -name:"Check for Test Failures"   
+       run |   
+         if [ -f test_failures.txt ]; then echo "One or more test suites failed." exit 1 else echo "All tests passed successfully." fi 
